# Generated by Django 5.0.2 on 2024-02-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='temp_field',
            field=models.BooleanField(default=True),
        ),
    ]
