# Generated by Django 5.0.2 on 2024-02-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='temp_field',
        ),
    ]
