# Generated by Django 3.2.24 on 2024-02-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_frontend_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
