# Generated by Django 5.0.2 on 2025-02-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sold'),
        ('products', '0006_product_sold_out'),
    ]

    operations = [
    ]
